const mappings = {
    // Argentine Stocks with ADRs
    // Formula: (ARS Price * Ratio) / ADR Price = CCL
    stocks: [
        { local: "BBAR", adr: "BBAR", ratio: 3 },
        { local: "BMA", adr: "BMA", ratio: 10 },
        { local: "CEPU", adr: "CEPU", ratio: 10 },
        { local: "CRES", adr: "CRESY", ratio: 10 },
        { local: "EDN", adr: "EDN", ratio: 20 },
        { local: "GGAL", adr: "GGAL", ratio: 10 },
        { local: "IRSA", adr: "IRS", ratio: 10 },
        { local: "LOMA", adr: "LOMA", ratio: 5 },
        { local: "PAMP", adr: "PAM", ratio: 25 },
        { local: "SUPV", adr: "SUPV", ratio: 5 },
        { local: "TECO2", adr: "TEO", ratio: 5 },
        { local: "TGSU2", adr: "TGS", ratio: 5 },
        { local: "YPFD", adr: "YPF", ratio: 1 }
    ],
    // CEDEARs with US mirror
    // Data from cedears_found_usa.md
    cedears: [
        // --- TUS CEDEARS ORIGINALES (Corregidos según PDF) ---
        { local: "AAPL", usa: "AAPL", ratio: 20 },
        { local: "AMZN", usa: "AMZN", ratio: 144 },
        { local: "MSFT", usa: "MSFT", ratio: 30 },
        { local: "GOOGL", usa: "GOOGL", ratio: 58 },
        { local: "META", usa: "META", ratio: 24 },
        { local: "TSLA", usa: "TSLA", ratio: 15 },
        { local: "NVDA", usa: "NVDA", ratio: 24 },
        { local: "NFLX", usa: "NFLX", ratio: 48 },
        { local: "PYPL", usa: "PYPL", ratio: 8 },
        { local: "INTC", usa: "INTC", ratio: 5 },
        { local: "AMD", usa: "AMD", ratio: 10 },
        { local: "WMT", usa: "WMT", ratio: 18 },
        { local: "KO", usa: "KO", ratio: 5 },
        { local: "DISN", usa: "DIS", ratio: 12 }, // Corregido: Ticker local es DISN y ratio es 12:1 según PDF
        { local: "V", usa: "V", ratio: 18 },
        { local: "MA", usa: "MA", ratio: 33 },
        { local: "BABA", usa: "BABA", ratio: 9 },
        { local: "BBD", usa: "BBD", ratio: 1 },
        { local: "SAN", usa: "SAN", ratio: 0.25 }, // Equivalente a 1:4 en el PDF
        { local: "JD", usa: "JD", ratio: 4 },
        { local: "TSM", usa: "TSM", ratio: 9 },
        { local: "VALE", usa: "VALE", ratio: 2 },
        { local: "DESP", usa: "DESP", ratio: 1 },
        { local: "MELI", usa: "MELI", ratio: 120 },
        { local: "GLOB", usa: "GLOB", ratio: 18 },
        { local: "PBR", usa: "PBR", ratio: 1 },
        { local: "MCD", usa: "MCD", ratio: 24 },
        { local: "NIO", usa: "NIO", ratio: 4 },
        { local: "T", usa: "T", ratio: 3 },
        { local: "XOM", usa: "XOM", ratio: 10 },
        { local: "FDX", usa: "FDX", ratio: 10 },
        { local: "GE", usa: "GE", ratio: 8 },
        { local: "GM", usa: "GM", ratio: 6 },
        { local: "JPM", usa: "JPM", ratio: 15 },
        { local: "JNJ", usa: "JNJ", ratio: 15 },
        { local: "NKE", usa: "NKE", ratio: 12 },
        { local: "SBUX", usa: "SBUX", ratio: 12 },
        { local: "UBER", usa: "UBER", ratio: 2 }, // Mantenido, pero no figura explícitamente en el PDF analizado
        { local: "WFC", usa: "WFC", ratio: 5 },
        { local: "CRM", usa: "CRM", ratio: 18 },
        { local: "SHOP", usa: "SHOP", ratio: 107 },
        { local: "MSTR", usa: "MSTR", ratio: 20 }, // Mantenido, pero no figura explícitamente en el PDF analizado
        { local: "COIN", usa: "COIN", ratio: 27 },
        { local: "PLTR", usa: "PLTR", ratio: 3 },
        { local: "SPY", usa: "SPY", ratio: 20 },

        // --- RESTO DE CEDEARS EXTRAÍDOS DEL PDF OFICIAL ---
        { local: "MMM", usa: "MMM", ratio: 10 },
        { local: "ABT", usa: "ABT", ratio: 4 },
        { local: "ABBV", usa: "ABBV", ratio: 10 },
        { local: "ANF", usa: "ANF", ratio: 1 },
        { local: "ACN", usa: "ACN", ratio: 75 },
        { local: "ADGO", usa: "AGRO", ratio: 1 },
        { local: "ADS", usa: "ADS", ratio: 22 },
        { local: "ADBE", usa: "ADBE", ratio: 44 },
        { local: "AAP", usa: "AAP", ratio: 14 },
        { local: "AEG", usa: "AEG", ratio: 1 },
        { local: "AEM", usa: "AEM", ratio: 6 },
        { local: "MO", usa: "MO", ratio: 4 },
        { local: "ABEV", usa: "ABEV", ratio: 0.333 },
        { local: "AMX", usa: "AMX", ratio: 1 },
        { local: "AAL", usa: "AAL", ratio: 2 },
        { local: "AXP", usa: "AXP", ratio: 15 },
        { local: "AIG", usa: "AIG", ratio: 5 },
        { local: "AMGN", usa: "AMGN", ratio: 30 },
        { local: "ADI", usa: "ADI", ratio: 15 },
        { local: "AMAT", usa: "AMAT", ratio: 5 },
        { local: "ARCO", usa: "ARCO", ratio: 0.5 },
        { local: "ARM", usa: "ARM", ratio: 27 },
        { local: "AZN", usa: "AZN", ratio: 4 },
        { local: "ADP", usa: "ADP", ratio: 6 },
        { local: "AVY", usa: "AVY", ratio: 18 },
        { local: "CAR", usa: "CAR", ratio: 26 },
        { local: "BIDU", usa: "BIDU", ratio: 11 },
        { local: "BKR", usa: "BKR", ratio: 7 },
        { local: "BBVA", usa: "BBVA", ratio: 1 },
        { local: "BSBR", usa: "BSBR", ratio: 1 },
        { local: "BA.C", usa: "BAC", ratio: 4 },
        { local: "BK", usa: "BK", ratio: 2 },
        { local: "BCS", usa: "BCS", ratio: 1 },
        { local: "GOLD", usa: "GOLD", ratio: 2 },
        { local: "BAS", usa: "BAS GR", ratio: 2 },
        { local: "BAYN", usa: "BAY GR", ratio: 3 },
        { local: "BRKB", usa: "BRK/B", ratio: 22 },
        { local: "BHP", usa: "BHP", ratio: 2 },
        { local: "BIOX", usa: "BIOX", ratio: 1 },
        { local: "BIB", usa: "BIIB", ratio: 13 },
        { local: "BB", usa: "BB", ratio: 3 },
        { local: "XYZ", usa: "XYZ", ratio: 20 },
        { local: "BA", usa: "BA", ratio: 24 },
        { local: "BKNG", usa: "BKNG", ratio: 700 },
        { local: "BP", usa: "BP", ratio: 5 },
        { local: "LND", usa: "LND", ratio: 1 },
        { local: "BAK", usa: "BAK", ratio: 2 },
        { local: "BRFS", usa: "BRFS", ratio: 0.333 },
        { local: "BMY", usa: "BMY", ratio: 3 },
        { local: "AVGO", usa: "AVGO", ratio: 39 },
        { local: "BNG", usa: "BG", ratio: 5 },
        { local: "CAH", usa: "CAH", ratio: 3 },
        { local: "CCL", usa: "CCL", ratio: 3 },
        { local: "CAT", usa: "CAT", ratio: 20 },
        { local: "CX", usa: "CX", ratio: 1 },
        { local: "EBR", usa: "EBR", ratio: 0.25 },
        { local: "SCHW", usa: "SCHW", ratio: 13 },
        { local: "CVX", usa: "CVX", ratio: 16 },
        { local: "CBD", usa: "CBD", ratio: 1 },
        { local: "SBS", usa: "SBS", ratio: 0.5 },
        { local: "SID", usa: "SID", ratio: 0.125 },
        { local: "CSCO", usa: "CSCO", ratio: 5 },
        { local: "C", usa: "C", ratio: 3 },
        { local: "KOFM", usa: "KOF", ratio: 2 },
        { local: "CDE", usa: "CDE", ratio: 1 },
        { local: "CL", usa: "CL", ratio: 3 },
        { local: "XLC", usa: "XLC", ratio: 19 },
        { local: "ELP", usa: "ELP", ratio: 0.333 },
        { local: "XLY", usa: "XLY", ratio: 43 },
        { local: "XLP", usa: "XLP", ratio: 16 },
        { local: "GLW", usa: "GLW", ratio: 4 },
        { local: "CAAP", usa: "CAAP", ratio: 0.25 },
        { local: "COST", usa: "COST", ratio: 48 },
        { local: "CVS", usa: "CVS", ratio: 15 },
        { local: "DHR", usa: "DHR", ratio: 54 },
        { local: "BSN", usa: "BSN GR", ratio: 20 },
        { local: "DE", usa: "DE", ratio: 40 },
        { local: "DAL", usa: "DAL", ratio: 8 },
        { local: "DTEA", usa: "DTEA GR", ratio: 3 },
        { local: "DEO", usa: "DEO", ratio: 6 },
        { local: "DOCU", usa: "DOCU", ratio: 22 },
        { local: "DOW", usa: "DOW", ratio: 6 },
        { local: "DD", usa: "DD", ratio: 5 },
        { local: "EOAN", usa: "EOAN GR", ratio: 6 },
        { local: "EBAY", usa: "EBAY", ratio: 2 },
        { local: "EA", usa: "EA", ratio: 14 },
        { local: "LLY", usa: "LLY", ratio: 56 },
        { local: "AKO B", usa: "AKO.B", ratio: 1 },
        { local: "ERJ", usa: "ERJ", ratio: 1 },
        { local: "E", usa: "E", ratio: 4 },
        { local: "EFX", usa: "EFX", ratio: 16 },
        { local: "EQNR", usa: "EQNR", ratio: 6 },
        { local: "ERIC", usa: "ERIC", ratio: 2 },
        { local: "ETSY", usa: "ETSY", ratio: 16 },
        { local: "FNMA", usa: "FNMA", ratio: 1 },
        { local: "RACE", usa: "RACE", ratio: 83 },
        { local: "FSLR", usa: "FSLR", ratio: 18 },
        { local: "FMX", usa: "FMX", ratio: 6 },
        { local: "FMCC", usa: "FMCC", ratio: 1 },
        { local: "FCX", usa: "FCX", ratio: 3 },
        { local: "GRMN", usa: "GRMN", ratio: 3 },
        { local: "GPRK", usa: "GPRK", ratio: 1 },
        { local: "GGB", usa: "GGB", ratio: 0.25 },
        { local: "GILD", usa: "GILD", ratio: 4 },
        { local: "GFI", usa: "GFI", ratio: 1 },
        { local: "GS", usa: "GS", ratio: 13 },
        { local: "GT", usa: "GT", ratio: 2 },
        { local: "PAC", usa: "PAC", ratio: 16 },
        { local: "ASR", usa: "ASR", ratio: 20 },
        { local: "TV", usa: "TV", ratio: 3 },
        { local: "GSK", usa: "GSK", ratio: 4 },
        { local: "HAL", usa: "HAL", ratio: 2 },
        { local: "HOG", usa: "HOG", ratio: 3 },
        { local: "HMY", usa: "HMY", ratio: 1 },
        { local: "HDB", usa: "HDB", ratio: 2 },
        { local: "XLV", usa: "XLV", ratio: 29 },
        { local: "HL", usa: "HL", ratio: 1 },
        { local: "HSY", usa: "HSY", ratio: 21 },
        { local: "HD", usa: "HD", ratio: 32 },
        { local: "HHPD LI", usa: "HNHPF", ratio: 2 },
        { local: "HMC", usa: "HMC", ratio: 1 },
        { local: "HON", usa: "HON", ratio: 8 },
        { local: "HWM", usa: "HWM", ratio: 1 },
        { local: "HPQ", usa: "HPQ", ratio: 1 },
        { local: "HSBC", usa: "HSBC", ratio: 2 },
        { local: "IBN", usa: "IBN", ratio: 1 },
        { local: "XLI", usa: "XLI", ratio: 28 },
        { local: "INFY", usa: "INFY", ratio: 1 },
        { local: "ING", usa: "ING", ratio: 3 },
        { local: "IP", usa: "IP", ratio: 4 },
        { local: "IBM", usa: "IBM", ratio: 15 },
        { local: "IFF", usa: "IFF", ratio: 12 },
        { local: "ISRG", usa: "ISRG", ratio: 90 },
        { local: "IBIT", usa: "IBIT", ratio: 10 },
        { local: "FXI", usa: "FXI", ratio: 5 },
        { local: "IEUR", usa: "IEUR", ratio: 11 },
        { local: "IBB", usa: "IBB", ratio: 27 },
        { local: "IVW", usa: "IVW", ratio: 20 },
        { local: "IVE", usa: "IVE", ratio: 40 },
        { local: "ITUB", usa: "JTUB", ratio: 1 },
        { local: "JCI", usa: "JCI", ratio: 2 },
        { local: "YY", usa: "YY", ratio: 5 },
        { local: "KB", usa: "KB", ratio: 2 },
        { local: "KMB", usa: "KMB", ratio: 6 },
        { local: "KGC", usa: "KGC", ratio: 1 },
        { local: "PHG", usa: "PHG", ratio: 5 },
        { local: "KEP", usa: "KEP", ratio: 1 },
        { local: "LRCX", usa: "LRCX", ratio: 66 },
        { local: "LVS", usa: "LVS", ratio: 2 },
        { local: "LAC", usa: "LAC", ratio: 1 },
        { local: "LAR", usa: "LAR", ratio: 1 },
        { local: "LYG", usa: "LYG", ratio: 2 },
        { local: "LMT", usa: "LMT", ratio: 20 },
        { local: "LKOD", usa: "LUKOY", ratio: 4 },
        { local: "MMC", usa: "MMC", ratio: 16 },
        { local: "MRVL", usa: "MRVL", ratio: 14 },
        { local: "XLB", usa: "XLB", ratio: 18 },
        { local: "MUX", usa: "MUX", ratio: 2 },
        { local: "MDT", usa: "MDT", ratio: 4 },
        { local: "MBG", usa: "MBG GR", ratio: 4 },
        { local: "MRK", usa: "MRK", ratio: 5 },
        { local: "MUFG", usa: "MUFG", ratio: 1 },
        { local: "MFG", usa: "MFG", ratio: 1 },
        { local: "MBT", usa: "MBT", ratio: 2 },
        { local: "MRNA", usa: "MRNA", ratio: 19 },
        { local: "MDLZ", usa: "MDLZ", ratio: 15 },
        { local: "MSI", usa: "MSI", ratio: 20 },
        { local: "NGG", usa: "NGG", ratio: 2 },
        { local: "NEC1", usa: "NEC1 GR", ratio: 0.333 },
        { local: "NTES", usa: "NTES", ratio: 14 },
        { local: "NEM", usa: "NEM", ratio: 3 },
        { local: "NXE", usa: "NXE", ratio: 1 },
        { local: "NSAN", usa: "NSANY", ratio: 1 },
        { local: "NOKA", usa: "NOK", ratio: 1 },
        { local: "NMR", usa: "NMR", ratio: 1 },
        { local: "NG", usa: "NG", ratio: 0.25 },
        { local: "NVS", usa: "NVS", ratio: 4 },
        { local: "NLM", usa: "NLMK", ratio: 2 },
        { local: "NU", usa: "NU", ratio: 2 },
        { local: "NUE", usa: "NUE", ratio: 16 },
        { local: "ORLY", usa: "ORLY", ratio: 222 },
        { local: "ORCL", usa: "ORCL", ratio: 3 },
        { local: "ORANY", usa: "ORANY", ratio: 1 },
        { local: "PCAR", usa: "PCAR", ratio: 3 },
        { local: "PAGS", usa: "PAGS", ratio: 3 },
        { local: "PAAS", usa: "PAAS", ratio: 3 },
        { local: "PSO", usa: "PSO", ratio: 1 },
        { local: "PEP", usa: "PEP", ratio: 18 },
        { local: "PFE", usa: "PFE", ratio: 4 },
        { local: "PM", usa: "PM", ratio: 18 },
        { local: "PSX", usa: "PSX", ratio: 6 },
        { local: "PINS", usa: "PINS", ratio: 7 },
        { local: "PBI", usa: "PBI", ratio: 1 },
        { local: "PKS", usa: "PKX", ratio: 3 },
        { local: "PG", usa: "PG", ratio: 15 },
        { local: "QCOM", usa: "OCOM", ratio: 11 },
        { local: "XLRE", usa: "XLRE", ratio: 9 },
        { local: "RIO", usa: "RIO", ratio: 8 },
        { local: "RIOT", usa: "RIOT", ratio: 3 },
        { local: "ROKU", usa: "ROKU", ratio: 13 },
        { local: "ROST", usa: "ROST", ratio: 4 },
        { local: "RTX", usa: "RTX", ratio: 5 },
        { local: "SMSN", usa: "SMSN LI", ratio: 14 },
        { local: "SAP", usa: "SAP", ratio: 6 },
        { local: "SLB", usa: "SLB", ratio: 3 },
        { local: "SE", usa: "SE", ratio: 32 },
        { local: "SHPWQ", usa: "SHPWQ", ratio: 0.5 },
        { local: "SHEL", usa: "SHEL", ratio: 2 },
        { local: "SIEGY", usa: "SIEGY", ratio: 3 },
        { local: "SWKS", usa: "SWKS", ratio: 21 },
        { local: "SNAP", usa: "SNAP", ratio: 1 },
        { local: "SNA", usa: "SNA", ratio: 6 },
        { local: "SNOW", usa: "SNOW", ratio: 30 },
        { local: "SONY", usa: "SONY", ratio: 8 },
        { local: "SCCO", usa: "SCCO", ratio: 2 },
        { local: "SPOT", usa: "SPOT", ratio: 28 },
        { local: "SPGI", usa: "SPGI", ratio: 45 },
        { local: "STLA", usa: "STLA", ratio: 5 },
        { local: "STNE", usa: "STNE", ratio: 3 },
        { local: "SDA", usa: "SDA", ratio: 2 },
        { local: "SUZ", usa: "SUZ", ratio: 1 },
        { local: "SYY", usa: "SYY", ratio: 8 },
        { local: "TGT", usa: "TGT", ratio: 24 },
        { local: "ATAD", usa: "DAOFY", ratio: 4 },
        { local: "XLK", usa: "XLK", ratio: 46 },
        { local: "TILAY", usa: "TIIAY", ratio: 1 },
        { local: "VIV", usa: "VIV", ratio: 1 },
        { local: "TEFO", usa: "TEF", ratio: 8 },
        { local: "TEN", usa: "TS", ratio: 1 },
        { local: "TXR", usa: "TX", ratio: 4 },
        { local: "TXN", usa: "TXN", ratio: 5 },
        { local: "TMO", usa: "TMO", ratio: 22 },
        { local: "TSU", usa: "TIMB", ratio: 1 },
        { local: "TJX", usa: "TJX", ratio: 22 },
        { local: "TTE", plain: "TTE", ratio: 3 },
        { local: "TM", usa: "TM", ratio: 15 },
        { local: "TRV", usa: "TRV", ratio: 6 },
        { local: "TCOM", usa: "TCOM", ratio: 2 },
        { local: "TRIP", usa: "TRIP", ratio: 2 },
        { local: "TWLO", usa: "TWLO", ratio: 36 },
        { local: "UGP", usa: "UGP", ratio: 1 },
        { local: "UL", usa: "UL", ratio: 3 },
        { local: "UNP", usa: "UNP", ratio: 20 },
        { local: "X", usa: "X", ratio: 3 },
        { local: "UNH", usa: "UNH", ratio: 33 },
        { local: "URBN", usa: "URBN", ratio: 2 },
        { local: "USB", usa: "USB", ratio: 5 },
        { local: "VEA", usa: "VEA", ratio: 10 },
        { local: "VRSN", usa: "VRSN", ratio: 6 },
        { local: "VZ", usa: "VZ", ratio: 4 },
        { local: "SPCE", usa: "SPCE", ratio: 0.5 },
        { local: "VIST", usa: "VIST US", ratio: 3 },
        { local: "VOD", usa: "VOD", ratio: 1 },
        { local: "WBA", usa: "WBA", ratio: 3 },
        { local: "WBO", usa: "WB", ratio: 6 },
        { local: "XRX", usa: "XRX", ratio: 1 },
        { local: "XP", usa: "XP", ratio: 4 },
        { local: "YZCA", usa: "YZCAY", ratio: 2 },
        { local: "YELP", usa: "YELP", ratio: 2 },
        { local: "ZM", usa: "ZM", ratio: 47 }
    ]
};

if (typeof module !== 'undefined' && module.exports) {
    module.exports = mappings;
} else {
    window.mappings = mappings;
}
